import type { INodeType, INodeTypeDescription } from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';

import { LIVECONNECT_BASE_URL, refreshTokenIfExpired } from './GenericFunctions';
import { liveConnectLoadOptions } from './LoadOptions';
import {
	assistantFields,
	assistantOperations,
	automationFields,
	automationOperations,
	categoryFields,
	categoryOperations,
	channelFields,
	channelOperations,
	contactFields,
	contactOperations,
	conversationFields,
	conversationOperations,
	crmFields,
	crmOperations,
	dealFields,
	dealOperations,
	dealTaskFields,
	dealTaskOperations,
	groupFields,
	groupOperations,
	historyFields,
	historyOperations,
	productFields,
	productOperations,
	proxyFields,
	proxyOperations,
	quickReplyFields,
	quickReplyOperations,
	topicFields,
	topicOperations,
	userFields,
	userOperations,
	wabaFields,
	wabaOperations,
	whatsAppFields,
	whatsAppOperations,
} from './descriptions';

export class LiveConnect implements INodeType {
	// Selectores dinámicos: alimentan los campos de ID con los endpoints de listado.
	methods = {
		loadOptions: liveConnectLoadOptions,
	};

	description: INodeTypeDescription = {
		displayName: 'LiveConnect',
		name: 'liveConnect',
		icon: { light: 'file:liveconnect2.svg', dark: 'file:liveconnect2.dark.svg' },
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'Interact with the LiveConnect API (omnichannel messaging + CRM)',
		defaults: {
			name: 'LiveConnect',
		},
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		usableAsTool: true,
		credentials: [
			{
				name: 'liveConnectApi',
				required: true,
			},
		],
		requestDefaults: {
			baseURL: LIVECONNECT_BASE_URL,
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
			},
		},
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				// preSend global: `resource` siempre está visible y es la primera propiedad,
				// así que su preSend corre en todas las operaciones y antes que cualquier
				// otro. Sin `property` no envía nada al body ni al query.
				routing: {
					send: { preSend: [refreshTokenIfExpired] },
				},
				options: [
					{ name: 'Assistant', value: 'assistant' },
					{ name: 'Category', value: 'category' },
					{ name: 'Channel', value: 'channel' },
					{ name: 'Contact', value: 'contact' },
					{ name: 'Conversation', value: 'conversation' },
					{ name: 'CRM', value: 'crm' },
					{ name: 'CRM Automation', value: 'automation' },
					{ name: 'Deal', value: 'deal' },
					{ name: 'Deal Task', value: 'dealTask' },
					{ name: 'History', value: 'history' },
					{ name: 'Product', value: 'product' },
					{ name: 'Proxy', value: 'proxy' },
					{ name: 'Quick Reply', value: 'quickReply' },
					{ name: 'Team', value: 'group' },
					{ name: 'Topic', value: 'topic' },
					{ name: 'User', value: 'user' },
					{ name: 'WhatsApp Business (WABA)', value: 'waba' },
					{ name: 'WhatsApp QR', value: 'whatsapp' },
				],
				default: 'contact',
			},

			...assistantOperations,
			...assistantFields,
			...automationOperations,
			...automationFields,
			...categoryOperations,
			...categoryFields,
			...channelOperations,
			...channelFields,
			...contactOperations,
			...contactFields,
			...conversationOperations,
			...conversationFields,
			...crmOperations,
			...crmFields,
			...dealOperations,
			...dealFields,
			...dealTaskOperations,
			...dealTaskFields,
			...groupOperations,
			...groupFields,
			...historyOperations,
			...historyFields,
			...productOperations,
			...productFields,
			...proxyOperations,
			...proxyFields,
			...quickReplyOperations,
			...quickReplyFields,
			...topicOperations,
			...topicFields,
			...userOperations,
			...userFields,
			...wabaOperations,
			...wabaFields,
			...whatsAppOperations,
			...whatsAppFields,

			{
				displayName: 'Return Full Response',
				name: 'fullResponse',
				type: 'boolean',
				default: false,
				description:
					'Whether to return the full API envelope ({ status, status_message, data }) instead of just the data field',
			},
		],
	};
}
