import type { INodeType, INodeTypeDescription } from 'n8n-workflow';

import { LIVECONNECT_BASE_URL, refreshTokenIfExpired } from './GenericFunctions';
import { liveConnectLoadOptions } from './LoadOptions';
import {
	assistantFields,
	assistantOperations,
	automationFields,
	automationOperations,
	categoryFields,
	categoryOperations,
	channelFields,
	channelOperations,
	contactFields,
	contactOperations,
	conversationFields,
	conversationOperations,
	crmFields,
	crmOperations,
	dealFields,
	dealOperations,
	dealTaskFields,
	dealTaskOperations,
	groupFields,
	groupOperations,
	historyFields,
	historyOperations,
	productFields,
	productOperations,
	proxyFields,
	proxyOperations,
	quickReplyFields,
	quickReplyOperations,
	topicFields,
	topicOperations,
	userFields,
	userOperations,
	wabaFields,
	wabaOperations,
	whatsAppFields,
	whatsAppOperations,
} from './descriptions';

export class LiveConnect implements INodeType {
	// Selectores dinámicos: alimentan los campos de ID con los endpoints de listado.
	methods = {
		loadOptions: liveConnectLoadOptions,
	};

	description: INodeTypeDescription = {
		displayName: 'LiveConnect',
		name: 'liveConnect',
		icon: 'file:liveconnect2.svg',
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'Interactúa con la API de LiveConnect (mensajería omnicanal + CRM)',
		defaults: {
			name: 'LiveConnect',
		},
		inputs: ['main'],
		outputs: ['main'],
		usableAsTool: true,
		credentials: [
			{
				name: 'liveConnectApi',
				required: true,
			},
		],
		requestDefaults: {
			baseURL: LIVECONNECT_BASE_URL,
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
			},
		},
		properties: [
			{
				displayName: 'Recurso',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				// preSend global: `resource` siempre está visible y es la primera propiedad,
				// así que su preSend corre en todas las operaciones y antes que cualquier
				// otro. Sin `property` no envía nada al body ni al query.
				routing: {
					send: { preSend: [refreshTokenIfExpired] },
				},
				options: [
					{ name: 'Asistente', value: 'assistant' },
					{ name: 'Automatización CRM', value: 'automation' },
					{ name: 'Canal', value: 'channel' },
					{ name: 'Categoría', value: 'category' },
					{ name: 'Contacto', value: 'contact' },
					{ name: 'Conversación', value: 'conversation' },
					{ name: 'CRM', value: 'crm' },
					{ name: 'Grupo', value: 'group' },
					{ name: 'Historial', value: 'history' },
					{ name: 'Negociación', value: 'deal' },
					{ name: 'Producto', value: 'product' },
					{ name: 'Proxy', value: 'proxy' },
					{ name: 'Respuesta Rápida', value: 'quickReply' },
					{ name: 'Tarea De Negociación', value: 'dealTask' },
					{ name: 'Tópico', value: 'topic' },
					{ name: 'Usuario', value: 'user' },
					{ name: 'WhatsApp Business (WABA)', value: 'waba' },
					{ name: 'WhatsApp QR', value: 'whatsapp' },
				],
				default: 'contact',
			},

			...assistantOperations,
			...assistantFields,
			...automationOperations,
			...automationFields,
			...categoryOperations,
			...categoryFields,
			...channelOperations,
			...channelFields,
			...contactOperations,
			...contactFields,
			...conversationOperations,
			...conversationFields,
			...crmOperations,
			...crmFields,
			...dealOperations,
			...dealFields,
			...dealTaskOperations,
			...dealTaskFields,
			...groupOperations,
			...groupFields,
			...historyOperations,
			...historyFields,
			...productOperations,
			...productFields,
			...proxyOperations,
			...proxyFields,
			...quickReplyOperations,
			...quickReplyFields,
			...topicOperations,
			...topicFields,
			...userOperations,
			...userFields,
			...wabaOperations,
			...wabaFields,
			...whatsAppOperations,
			...whatsAppFields,

			{
				displayName: 'Devolver Respuesta Completa',
				name: 'fullResponse',
				type: 'boolean',
				default: false,
				description:
					'Si se activa, devuelve el envelope completo del API ({ status, status_message, data }) en lugar de solo el campo data',
			},
		],
	};
}
